### ISSUE TITLE
helper function for no_op

### ISSUE THREAD

**Issue by fidel-bello** [fidel-bello/camera_angles_mod#12]
- have a helper function that takes in number of bytes and takes in value to dynamically return our own no_op 
- at the moment the nop_test function has Nop[ ] manually inserted to WriteProcessMemory
- would like to have a helper that dynamically creates our nops according to the bytes we input
```c++

/*
* n is the bytes of our address. in this case it was 4;
* Nop is NOP we have defined in our camera_hack.h file
* i believe this should work 
*/
int no_op(int n, BYTES Nop)
{
   //should return [n of Nop];
// the output should be nop = { x90, x90, x90, x90 }
}

```

**Comment by delinx** [comment]
You basically should use array at this point, in C it would be something like this, with C++ you better use the New method
```C
char array*;
memset(array, 0x90, sizeof(char) * n);
return array
```
Something along the lines of
```C++
int array[n] = { 0x90 };
```
could work

**Comment by fidel-bello** [comment]
> You basically should use array at this point, in C it would be something like this, with C++ you better use the New method
> 
> ```c
> char array*;
> memset(array, 0x90, sizeof(char) * n);
> return array
> ```
> 
> Something along the lines of

ooohhhh, this is the right way of using memset. nice!

**Comment by delinx** [comment]
C++ prefers you use new keyword instead, I actually think you can get away with
```C++
int array[n] = { 0x90 };
return array[]
```
Although apparently depending on the compiler it might not allow this without a new keyword, since the size of N is unknown at a compile time, arrays made with new do no have fill in function like one above, but you can fill it up with a loop within your interface function for cooking arrays of nops
